-- Short form cues per exercise, shown in the exercise detail sheet and the
-- log-set sheet. Written by hand (not sourced from any image/video library)
-- since the catalog has no exercise media at all yet — this is the
-- lowest-effort way to stop a picked exercise being just a bare name.
ALTER TABLE exercises ADD COLUMN instructions TEXT NOT NULL DEFAULT '';

UPDATE exercises SET instructions = CASE name
    WHEN 'Barbell Bench Press' THEN 'Lie flat, grip just outside shoulder width. Lower the bar to your mid-chest with control, then press up until arms are extended. Keep shoulder blades pinched and feet planted.'
    WHEN 'Barbell Back Squat' THEN 'Bar rests on your upper traps. Break at the hips and knees together, sit back until thighs are at least parallel, then drive through your whole foot to stand.'
    WHEN 'Conventional Deadlift' THEN 'Feet hip-width, bar over mid-foot. Hinge down to grip it, chest up, back flat. Drive through the floor and stand tall, keeping the bar close to your legs throughout.'
    WHEN 'Overhead Press' THEN 'Bar at collarbone height, grip just outside shoulders. Brace your core and press straight overhead, tucking your head through at the top. Avoid arching your lower back.'
    WHEN 'Pull-Up' THEN 'Hang from the bar with a full grip, arms extended. Pull your chest toward the bar by driving your elbows down, then lower under control to a full hang.'
    WHEN 'Barbell Row' THEN 'Hinge forward with a flat back, bar hanging at arm''s length. Pull the bar to your lower ribs, squeezing your shoulder blades together, then lower with control.'
    WHEN 'Dumbbell Bicep Curl' THEN 'Stand with a dumbbell in each hand, elbows tucked at your sides. Curl the weight up without swinging, squeeze at the top, then lower slowly.'
    WHEN 'Triceps Pushdown' THEN 'Grip the cable attachment with elbows pinned to your sides. Extend your forearms down until arms are straight, then return under control without flaring your elbows.'
    WHEN 'Leg Press' THEN 'Feet shoulder-width on the platform. Lower until knees reach about 90 degrees, then press through your heels to extend without locking your knees hard at the top.'
    WHEN 'Plank' THEN 'Forearms and toes on the floor, body in a straight line from head to heels. Brace your core and glutes, and avoid letting your hips sag or pike up.'
    WHEN 'Incline Dumbbell Press' THEN 'On an incline bench, press dumbbells from shoulder height straight up until arms are extended, then lower with control to a stretch at your chest.'
    WHEN 'Dumbbell Shoulder Press' THEN 'Seated or standing, start with dumbbells at shoulder height. Press straight overhead until arms extend, then lower back to shoulder height under control.'
    WHEN 'Push-Up' THEN 'Hands under shoulders, body in a straight line. Lower your chest toward the floor with elbows at roughly 45 degrees, then push back up to full extension.'
    WHEN 'Chest Press Machine' THEN 'Adjust the seat so handles align with your chest. Press forward until arms extend, then return under control without letting the weight stack slam.'
    WHEN 'Cable Chest Fly' THEN 'Cables set at chest height, slight bend in the elbows. Bring your hands together in front of your chest in an arcing motion, then return with control.'
    WHEN 'Dips' THEN 'Support yourself on parallel bars, lean slightly forward. Lower until your shoulders dip below your elbows, then press back up to full extension.'
    WHEN 'Lateral Raise' THEN 'Dumbbells at your sides, slight bend in the elbows. Raise your arms out to the sides until roughly shoulder height, then lower slowly — avoid swinging the weight up.'
    WHEN 'Pike Push-Up' THEN 'Hips high in an inverted-V position, hands shoulder-width. Lower the top of your head toward the floor by bending your elbows, then press back up.'
    WHEN 'Lat Pulldown' THEN 'Grip the bar wider than shoulder width. Pull it down to your upper chest by driving your elbows down and back, then let it rise under control.'
    WHEN 'Seated Cable Row' THEN 'Sit tall with knees slightly bent. Pull the handle to your lower ribs, squeezing your shoulder blades together, then extend your arms forward with control.'
    WHEN 'Dumbbell Row' THEN 'One knee and hand supported on a bench, back flat. Row the dumbbell to your hip, driving your elbow up and back, then lower with control.'
    WHEN 'Inverted Row' THEN 'Under a bar set at hip height, body straight, heels on the floor. Pull your chest to the bar by squeezing your shoulder blades, then lower under control.'
    WHEN 'Chin-Up' THEN 'Hang from the bar with an underhand grip, shoulder-width. Pull your chin above the bar leading with your chest, then lower under control.'
    WHEN 'T-Bar Row Machine' THEN 'Chest supported, grip the handles. Row your elbows back and up, squeezing your shoulder blades, then extend your arms fully under control.'
    WHEN 'Face Pull' THEN 'Cable set above head height. Pull the rope toward your face, flaring your elbows out and rotating your hands back, then extend forward with control.'
    WHEN 'Barbell Curl' THEN 'Stand with an underhand, shoulder-width grip. Curl the bar up without swinging your torso, squeeze at the top, then lower slowly.'
    WHEN 'Hammer Curl' THEN 'Dumbbells at your sides with palms facing your body. Curl straight up keeping that neutral grip throughout, then lower with control.'
    WHEN 'Romanian Deadlift' THEN 'Bar at hip height, soft knees. Push your hips back while lowering the bar close to your legs, feeling a hamstring stretch, then drive your hips forward to stand.'
    WHEN 'Dumbbell Lunge' THEN 'Dumbbells at your sides, step forward into a lunge until both knees reach about 90 degrees, then push back through your front foot to the start.'
    WHEN 'Bodyweight Squat' THEN 'Feet shoulder-width. Sit back and down until thighs are at least parallel to the floor, keeping your chest up, then drive up through your whole foot.'
    WHEN 'Bulgarian Split Squat' THEN 'Rear foot elevated behind you on a bench. Lower your back knee toward the floor, then drive through your front foot to stand back up.'
    WHEN 'Leg Curl Machine' THEN 'Lie face down with the pad against your ankles. Curl your heels toward your glutes, squeeze, then lower under control without letting the weight stack slam.'
    WHEN 'Leg Extension Machine' THEN 'Seated with the pad against your shins. Extend your legs until nearly straight, squeeze your quads, then lower with control.'
    WHEN 'Hip Thrust' THEN 'Upper back on a bench, bar over your hips. Drive through your heels to raise your hips until your body is a straight line, squeeze your glutes, then lower.'
    WHEN 'Glute Bridge' THEN 'Lie on your back, knees bent, feet flat. Drive through your heels to raise your hips until your body is a straight line, squeeze, then lower with control.'
    WHEN 'Walking Lunge' THEN 'Step forward into a lunge until both knees reach about 90 degrees, then drive up and forward into the next step, alternating legs.'
    WHEN 'Goblet Squat' THEN 'Hold a dumbbell vertically at your chest. Squat down between your knees, keeping your chest up, then drive through your whole foot to stand.'
    WHEN 'Cable Curl' THEN 'Stand facing the cable stack with a low attachment. Curl the handle up without swinging your torso, squeeze at the top, then lower slowly.'
    WHEN 'Overhead Triceps Extension' THEN 'Hold a dumbbell overhead with both hands. Lower it behind your head by bending your elbows, keeping upper arms still, then extend back up.'
    WHEN 'Close-Grip Bench Press' THEN 'Grip the bar just inside shoulder width. Lower it to your lower chest keeping elbows tucked, then press up to full extension.'
    WHEN 'Diamond Push-Up' THEN 'Hands together under your chest forming a diamond shape. Lower your chest toward your hands with elbows tucked, then press back up.'
    WHEN 'Crunch' THEN 'Lie on your back, knees bent, hands lightly behind your head. Curl your shoulders off the floor by contracting your abs, then lower with control.'
    WHEN 'Hanging Leg Raise' THEN 'Hang from a bar with arms extended. Raise your legs until roughly parallel to the floor (or higher) by curling your pelvis, then lower with control.'
    WHEN 'Cable Woodchop' THEN 'Cable set high, stand sideways to the stack. Pull the handle down and across your body in a chopping motion, rotating through your torso, then return with control.'
    WHEN 'Russian Twist' THEN 'Sit with knees bent, torso leaned back slightly, feet lifted if able. Rotate your torso side to side, tapping the floor beside your hip each time.'
    WHEN 'Dumbbell Bench Press' THEN 'Lie flat with a dumbbell in each hand at chest height. Press up until arms extend, then lower with control to a stretch at your chest.'
    ELSE instructions
END;
