// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/google/uuid"
)

type Accessory struct {
	ID         uuid.UUID `json:"id"`
	Code       string    `json:"code"`
	Name       string    `json:"name"`
	Slot       string    `json:"slot"`
	UnlockHint string    `json:"unlockHint"`
}

type AuthPayload struct {
	User         *User  `json:"user"`
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
}

type BodyMetric struct {
	ID         uuid.UUID `json:"id"`
	MetricType string    `json:"metricType"`
	Value      float64   `json:"value"`
	RecordedAt time.Time `json:"recordedAt"`
}

type CreateProgramInput struct {
	Name string             `json:"name"`
	Days []*ProgramDayInput `json:"days"`
}

type Exercise struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	Category     string    `json:"category"`
	MuscleGroups []string  `json:"muscleGroups"`
	Equipment    string    `json:"equipment"`
	IsCustom     bool      `json:"isCustom"`
	Instructions string    `json:"instructions"`
}

type ExerciseInput struct {
	Name         string   `json:"name"`
	Category     string   `json:"category"`
	MuscleGroups []string `json:"muscleGroups"`
	Equipment    string   `json:"equipment"`
}

type ExerciseTarget struct {
	ExerciseID        uuid.UUID `json:"exerciseId"`
	TargetSets        int       `json:"targetSets"`
	TargetReps        *int      `json:"targetReps,omitempty"`
	SuggestedWeightKg float64   `json:"suggestedWeightKg"`
	WeekNumber        int       `json:"weekNumber"`
	Reasoning         string    `json:"reasoning"`
}

type FitnessProfileInput struct {
	Goal              FitnessGoal     `json:"goal"`
	ExperienceLevel   ExperienceLevel `json:"experienceLevel"`
	DaysPerWeek       int             `json:"daysPerWeek"`
	EquipmentAccess   []string        `json:"equipmentAccess"`
	AvoidMuscleGroups []string        `json:"avoidMuscleGroups"`
}

type LogSetResult struct {
	Set        *WorkoutSet       `json:"set"`
	NewRecords []*PersonalRecord `json:"newRecords"`
}

type Mutation struct {
}

type NextWorkout struct {
	Program    *Program    `json:"program"`
	Day        *ProgramDay `json:"day"`
	WeekNumber int         `json:"weekNumber"`
}

type PageInfo struct {
	HasNextPage bool    `json:"hasNextPage"`
	EndCursor   *string `json:"endCursor,omitempty"`
}

type PersonalRecord struct {
	ID           uuid.UUID `json:"id"`
	ExerciseID   uuid.UUID `json:"exerciseId"`
	RecordType   string    `json:"recordType"`
	Value        float64   `json:"value"`
	AchievedAt   time.Time `json:"achievedAt"`
	WorkoutSetID uuid.UUID `json:"workoutSetId"`
}

type Pet struct {
	ID                  uuid.UUID       `json:"id"`
	Name                string          `json:"name"`
	Species             PetSpecies      `json:"species"`
	Color               PetColor        `json:"color"`
	Stage               PetStage        `json:"stage"`
	StageLabel          string          `json:"stageLabel"`
	Mood                int             `json:"mood"`
	MoodState           MoodState       `json:"moodState"`
	CurrentStreak       int             `json:"currentStreak"`
	LongestStreak       int             `json:"longestStreak"`
	WorkoutsToNextStage *int            `json:"workoutsToNextStage,omitempty"`
	HatchedAt           *time.Time      `json:"hatchedAt,omitempty"`
	Appearance          *PetAppearance  `json:"appearance"`
	Accessories         []*PetAccessory `json:"accessories"`
	NewlyUnlocked       []*PetAccessory `json:"newlyUnlocked"`
}

type PetAccessory struct {
	Accessory  *Accessory `json:"accessory"`
	UnlockedAt time.Time  `json:"unlockedAt"`
	Equipped   bool       `json:"equipped"`
}

type PetAppearance struct {
	BodyAssetKey       string   `json:"bodyAssetKey"`
	ExpressionAssetKey string   `json:"expressionAssetKey"`
	Tint               string   `json:"tint"`
	Layers             []string `json:"layers"`
}

type PlateauStatus struct {
	IsPlateaued   bool    `json:"isPlateaued"`
	CurrentBestKg float64 `json:"currentBestKg"`
	Message       string  `json:"message"`
}

type Program struct {
	ID              uuid.UUID       `json:"id"`
	Name            string          `json:"name"`
	Goal            FitnessGoal     `json:"goal"`
	DaysPerWeek     int             `json:"daysPerWeek"`
	Notes           string          `json:"notes"`
	CreatedAt       time.Time       `json:"createdAt"`
	Days            []*ProgramDay   `json:"days"`
	IsActive        bool            `json:"isActive"`
	ProgressionRule ProgressionRule `json:"progressionRule"`
}

type ProgramDay struct {
	ID       uuid.UUID        `json:"id"`
	DayLabel string           `json:"dayLabel"`
	Position int              `json:"position"`
	Template *WorkoutTemplate `json:"template"`
}

type ProgramDayInput struct {
	DayLabel   string    `json:"dayLabel"`
	TemplateID uuid.UUID `json:"templateId"`
}

type ProgressPoint struct {
	Day         time.Time `json:"day"`
	TotalVolume float64   `json:"totalVolume"`
	MaxWeight   float64   `json:"maxWeight"`
	MaxReps     int       `json:"maxReps"`
	SetCount    int       `json:"setCount"`
}

type ProgressionSuggestion struct {
	SuggestedWeightKg float64  `json:"suggestedWeightKg"`
	SuggestedReps     int      `json:"suggestedReps"`
	Reasoning         string   `json:"reasoning"`
	BasedOnRpe        *float64 `json:"basedOnRpe,omitempty"`
}

type Query struct {
}

type Subscription struct {
}

type TemplateExercise struct {
	ID            uuid.UUID `json:"id"`
	ExerciseID    uuid.UUID `json:"exerciseId"`
	Position      int       `json:"position"`
	TargetSets    int       `json:"targetSets"`
	TargetReps    *int      `json:"targetReps,omitempty"`
	SupersetGroup *int      `json:"supersetGroup,omitempty"`
}

type TemplateExerciseInput struct {
	ExerciseID    uuid.UUID `json:"exerciseId"`
	TargetSets    int       `json:"targetSets"`
	TargetReps    *int      `json:"targetReps,omitempty"`
	SupersetGroup *int      `json:"supersetGroup,omitempty"`
}

type User struct {
	ID          uuid.UUID `json:"id"`
	Email       string    `json:"email"`
	DisplayName string    `json:"displayName"`
	Timezone    string    `json:"timezone"`
	CreatedAt   time.Time `json:"createdAt"`
}

type UserFitnessProfile struct {
	Goal              FitnessGoal     `json:"goal"`
	ExperienceLevel   ExperienceLevel `json:"experienceLevel"`
	DaysPerWeek       int             `json:"daysPerWeek"`
	EquipmentAccess   []string        `json:"equipmentAccess"`
	AvoidMuscleGroups []string        `json:"avoidMuscleGroups"`
	UpdatedAt         time.Time       `json:"updatedAt"`
}

type Workout struct {
	ID         uuid.UUID     `json:"id"`
	StartedAt  time.Time     `json:"startedAt"`
	EndedAt    *time.Time    `json:"endedAt,omitempty"`
	Notes      string        `json:"notes"`
	Status     WorkoutStatus `json:"status"`
	Sets       []*WorkoutSet `json:"sets"`
	TemplateID *uuid.UUID    `json:"templateId,omitempty"`
}

type WorkoutConnection struct {
	Edges    []*WorkoutEdge `json:"edges"`
	PageInfo *PageInfo      `json:"pageInfo"`
}

type WorkoutEdge struct {
	Cursor string   `json:"cursor"`
	Node   *Workout `json:"node"`
}

type WorkoutSet struct {
	ID          uuid.UUID  `json:"id"`
	ExerciseID  uuid.UUID  `json:"exerciseId"`
	SetNumber   int        `json:"setNumber"`
	Reps        int        `json:"reps"`
	WeightKg    float64    `json:"weightKg"`
	Rpe         *float64   `json:"rpe,omitempty"`
	SetType     SetType    `json:"setType"`
	SupersetID  *uuid.UUID `json:"supersetId,omitempty"`
	PerformedAt time.Time  `json:"performedAt"`
}

type WorkoutTemplate struct {
	ID        uuid.UUID           `json:"id"`
	Name      string              `json:"name"`
	CreatedAt time.Time           `json:"createdAt"`
	Exercises []*TemplateExercise `json:"exercises"`
}

type ExperienceLevel string

const (
	ExperienceLevelBeginner     ExperienceLevel = "BEGINNER"
	ExperienceLevelIntermediate ExperienceLevel = "INTERMEDIATE"
	ExperienceLevelAdvanced     ExperienceLevel = "ADVANCED"
)

var AllExperienceLevel = []ExperienceLevel{
	ExperienceLevelBeginner,
	ExperienceLevelIntermediate,
	ExperienceLevelAdvanced,
}

func (e ExperienceLevel) IsValid() bool {
	switch e {
	case ExperienceLevelBeginner, ExperienceLevelIntermediate, ExperienceLevelAdvanced:
		return true
	}
	return false
}

func (e ExperienceLevel) String() string {
	return string(e)
}

func (e *ExperienceLevel) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ExperienceLevel(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ExperienceLevel", str)
	}
	return nil
}

func (e ExperienceLevel) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ExperienceLevel) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ExperienceLevel) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type FitnessGoal string

const (
	FitnessGoalStrength       FitnessGoal = "STRENGTH"
	FitnessGoalHypertrophy    FitnessGoal = "HYPERTROPHY"
	FitnessGoalFatLoss        FitnessGoal = "FAT_LOSS"
	FitnessGoalGeneralFitness FitnessGoal = "GENERAL_FITNESS"
)

var AllFitnessGoal = []FitnessGoal{
	FitnessGoalStrength,
	FitnessGoalHypertrophy,
	FitnessGoalFatLoss,
	FitnessGoalGeneralFitness,
}

func (e FitnessGoal) IsValid() bool {
	switch e {
	case FitnessGoalStrength, FitnessGoalHypertrophy, FitnessGoalFatLoss, FitnessGoalGeneralFitness:
		return true
	}
	return false
}

func (e FitnessGoal) String() string {
	return string(e)
}

func (e *FitnessGoal) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FitnessGoal(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FitnessGoal", str)
	}
	return nil
}

func (e FitnessGoal) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *FitnessGoal) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e FitnessGoal) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type MoodState string

const (
	MoodStateHappy     MoodState = "HAPPY"
	MoodStateContent   MoodState = "CONTENT"
	MoodStateLow       MoodState = "LOW"
	MoodStateNeglected MoodState = "NEGLECTED"
)

var AllMoodState = []MoodState{
	MoodStateHappy,
	MoodStateContent,
	MoodStateLow,
	MoodStateNeglected,
}

func (e MoodState) IsValid() bool {
	switch e {
	case MoodStateHappy, MoodStateContent, MoodStateLow, MoodStateNeglected:
		return true
	}
	return false
}

func (e MoodState) String() string {
	return string(e)
}

func (e *MoodState) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MoodState(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MoodState", str)
	}
	return nil
}

func (e MoodState) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MoodState) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MoodState) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PetColor string

const (
	PetColorGreen  PetColor = "GREEN"
	PetColorRed    PetColor = "RED"
	PetColorBlue   PetColor = "BLUE"
	PetColorAmber  PetColor = "AMBER"
	PetColorViolet PetColor = "VIOLET"
)

var AllPetColor = []PetColor{
	PetColorGreen,
	PetColorRed,
	PetColorBlue,
	PetColorAmber,
	PetColorViolet,
}

func (e PetColor) IsValid() bool {
	switch e {
	case PetColorGreen, PetColorRed, PetColorBlue, PetColorAmber, PetColorViolet:
		return true
	}
	return false
}

func (e PetColor) String() string {
	return string(e)
}

func (e *PetColor) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PetColor(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PetColor", str)
	}
	return nil
}

func (e PetColor) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PetColor) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PetColor) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PetSpecies string

const (
	PetSpeciesSprout PetSpecies = "SPROUT"
	PetSpeciesEmber  PetSpecies = "EMBER"
	PetSpeciesPebble PetSpecies = "PEBBLE"
	PetSpeciesDrift  PetSpecies = "DRIFT"
)

var AllPetSpecies = []PetSpecies{
	PetSpeciesSprout,
	PetSpeciesEmber,
	PetSpeciesPebble,
	PetSpeciesDrift,
}

func (e PetSpecies) IsValid() bool {
	switch e {
	case PetSpeciesSprout, PetSpeciesEmber, PetSpeciesPebble, PetSpeciesDrift:
		return true
	}
	return false
}

func (e PetSpecies) String() string {
	return string(e)
}

func (e *PetSpecies) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PetSpecies(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PetSpecies", str)
	}
	return nil
}

func (e PetSpecies) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PetSpecies) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PetSpecies) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PetStage string

const (
	PetStageEgg       PetStage = "EGG"
	PetStageHatchling PetStage = "HATCHLING"
	PetStageJuvenile  PetStage = "JUVENILE"
	PetStageAdult     PetStage = "ADULT"
	PetStageChampion  PetStage = "CHAMPION"
)

var AllPetStage = []PetStage{
	PetStageEgg,
	PetStageHatchling,
	PetStageJuvenile,
	PetStageAdult,
	PetStageChampion,
}

func (e PetStage) IsValid() bool {
	switch e {
	case PetStageEgg, PetStageHatchling, PetStageJuvenile, PetStageAdult, PetStageChampion:
		return true
	}
	return false
}

func (e PetStage) String() string {
	return string(e)
}

func (e *PetStage) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PetStage(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PetStage", str)
	}
	return nil
}

func (e PetStage) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PetStage) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PetStage) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ProgressionRule string

const (
	ProgressionRuleLinear            ProgressionRule = "LINEAR"
	ProgressionRuleDoubleProgression ProgressionRule = "DOUBLE_PROGRESSION"
	ProgressionRuleNone              ProgressionRule = "NONE"
)

var AllProgressionRule = []ProgressionRule{
	ProgressionRuleLinear,
	ProgressionRuleDoubleProgression,
	ProgressionRuleNone,
}

func (e ProgressionRule) IsValid() bool {
	switch e {
	case ProgressionRuleLinear, ProgressionRuleDoubleProgression, ProgressionRuleNone:
		return true
	}
	return false
}

func (e ProgressionRule) String() string {
	return string(e)
}

func (e *ProgressionRule) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ProgressionRule(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ProgressionRule", str)
	}
	return nil
}

func (e ProgressionRule) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ProgressionRule) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ProgressionRule) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SetType string

const (
	SetTypeNormal  SetType = "NORMAL"
	SetTypeWarmup  SetType = "WARMUP"
	SetTypeDropset SetType = "DROPSET"
	SetTypeFailure SetType = "FAILURE"
)

var AllSetType = []SetType{
	SetTypeNormal,
	SetTypeWarmup,
	SetTypeDropset,
	SetTypeFailure,
}

func (e SetType) IsValid() bool {
	switch e {
	case SetTypeNormal, SetTypeWarmup, SetTypeDropset, SetTypeFailure:
		return true
	}
	return false
}

func (e SetType) String() string {
	return string(e)
}

func (e *SetType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SetType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SetType", str)
	}
	return nil
}

func (e SetType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SetType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SetType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type WorkoutStatus string

const (
	WorkoutStatusInProgress WorkoutStatus = "IN_PROGRESS"
	WorkoutStatusCompleted  WorkoutStatus = "COMPLETED"
)

var AllWorkoutStatus = []WorkoutStatus{
	WorkoutStatusInProgress,
	WorkoutStatusCompleted,
}

func (e WorkoutStatus) IsValid() bool {
	switch e {
	case WorkoutStatusInProgress, WorkoutStatusCompleted:
		return true
	}
	return false
}

func (e WorkoutStatus) String() string {
	return string(e)
}

func (e *WorkoutStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = WorkoutStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid WorkoutStatus", str)
	}
	return nil
}

func (e WorkoutStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *WorkoutStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e WorkoutStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
